name: ❓ Question
description: Ask a question about PostXAgent
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: What is your question about?
      options:
        - Installation / Setup
        - Configuration
        - Laravel Backend
        - AI Manager (C#)
        - Social Media Integration
        - AI Providers
        - API Usage
        - Deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any additional context or details that might help us answer your question
    validations:
      required: false

  - type: textarea
    id: tried
    attributes:
      label: What Have You Tried?
      description: What have you already tried or researched?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched for similar questions
          required: true
